spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  profiles:
    active: local
  mvc:
    static-path-pattern: "/static/**"

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    in.stonecolddev.hpg: "debug"

pebble:
  suffix: .html
  cache: true

feeds:
  cacheExpire: PT1h # default to 1 hour
  feedSources:
    -
      name: hackernews
      uri: https://news.ycombinator.com/rss
      type: rss
    -
      name: jooq
      uri: http://blog.jooq.org/feed/
      type: rss
    -
      name: joda
      uri: http://blog.joda.org/feeds/posts/default
      type: rss
