name: blood ocean
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
      - name: Checkout
        uses: actions/checkout@v1
      - run: git checkout ${{ github.ref_name }}
      - name: Cache maven packages
        env:
          cache-name: cache-maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.18
      - name: Generate coverage report
        run: mvn clean -Dgroups=unit-test jacoco:prepare-agent install jacoco:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco/
          fail_ci_if_error: true
          verbose: true